# Generated by Django 2.0.13 on 2019-11-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191115_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='news_url',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
